# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15e0eK91GJsO5m2u4bdkMUtY-9rN3gu1B
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# from torchvision import transforms
# from PIL import Image
# import os
# import base64
# from openai import OpenAI
# from google import genai
# from google.genai import types
# 
# # --- 1. Page Configuration ---
# st.set_page_config(
#     page_title="Food-11 Classifier",
#     page_icon="🍲",
#     layout="centered"
# )
# st.title("🍲 Food-11 Classifier App")
# st.write("Upload an image of food to classify it using your trained CNN model or compare it with GPT-4o and Gemini.")
# 
# # --- 2. Re-instantiate Architecture ---
# class SimpleCNN(nn.Module):
#     def __init__(self, num_classes=11, p=0.5):
#         super(SimpleCNN, self).__init__()
#         self.conv1 = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, padding=1)
#         self.bn1 = nn.BatchNorm2d(32)
#         self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
# 
#         self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)
#         self.bn2 = nn.BatchNorm2d(64)
# 
#         self.conv3 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
#         self.bn3 = nn.BatchNorm2d(128)
# 
#         self.dropout = nn.Dropout(p=p)
# 
#         # Global pooling layer
#         self.global_pool = nn.AdaptiveAvgPool2d((1, 1))
#         self.fc1 = nn.Linear(128, 256)
#         self.fc2 = nn.Linear(256, num_classes)
# 
#     def forward(self, x):
#         x = self.pool(F.relu(self.bn1(self.conv1(x))))
#         x = self.pool(F.relu(self.bn2(self.conv2(x))))
#         x = self.pool(F.relu(self.bn3(self.conv3(x))))
# 
#         x = self.global_pool(x)
#         x = torch.flatten(x, 1)
# 
#         x = F.relu(self.fc1(x))
#         x = self.dropout(x)
#         x = self.fc2(x)
#         return x
# 
# # --- 3. Cached Model Loader ---
# @st.cache_resource
# def load_model():
#     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#     class_names = ['Bread', 'Dairy product', 'Dessert', 'Egg', 'Fried food',
#                    'Meat', 'Noodles-Pasta', 'Rice', 'Seafood', 'Soup', 'Vegetable-Fruit']
#     model = SimpleCNN(num_classes=len(class_names), p=0.5)
#     if os.path.exists("food11_simple_cnn.pth"):
#         model.load_state_dict(torch.load("food11_simple_cnn.pth", map_location=device))
#     model.to(device)
#     model.eval()
#     return model, class_names, device
# 
# model, class_names, device = load_model()
# 
# # --- 4. OpenAI Classification Function ---
# def classify_image_with_gpt(image_bytes, class_names):
#     api_key = os.environ.get("OPENAI_API_KEY")
#     if not api_key:
#         return "Error: OPENAI_API_KEY environment variable is not set."
# 
#     try:
#         client = OpenAI(api_key=api_key)
#         base64_image = base64.b64encode(image_bytes).decode('utf-8')
#         response = client.chat.completions.create(
#             model="gpt-4o",
#             messages=[
#                 {
#                     "role": "user",
#                     "content": [
#                         {
#                             "type": "text",
#                             "text": f"Classify this food image into exactly one of these 11 categories: {class_names}. Return just the category name."
#                         },
#                         {
#                             "type": "image_url",
#                             "image_url": {
#                                 "url": f"data:image/jpeg;base64,{base64_image}"
#                             }
#                         }
#                     ]
#                 }
#             ],
#             max_tokens=30
#         )
#         return response.choices[0].message.content.strip()
#     except Exception as e:
#         return f"Error: {str(e)}"
# 
# # --- 5. Gemini Classification Function ---
# def classify_image_with_gemini(image, class_names):
#     try:
#         client = genai.Client()
#         prompt = f"Classify this food image into exactly one of these 11 categories: {class_names}. Return just the category name."
# 
#         response = client.models.generate_content(
#             model='gemini-3.5-flash',
#             contents=[image, prompt]
#         )
#         return response.text.strip()
#     except Exception as e:
#         return f"Error: {str(e)}"
# 
# # --- 6. Image Preprocessing Pipeline ---
# transform = transforms.Compose([
#     transforms.Resize((224, 224)),
#     transforms.ToTensor(),
#     transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
# ])
# 
# # --- 7. Sidebar / Metrics Section ---
# st.sidebar.header("📊 Model Metrics & Info")
# st.sidebar.markdown(f"**Architecture:** SimpleCNN")
# st.sidebar.markdown(f"**Total Classes:** {len(class_names)}")
# st.sidebar.markdown(f"**Device:** {device}")
# 
# # --- 8. File Uploader & Prediction ---
# uploaded_file = st.file_uploader("Choose a food image...", type=["jpg", "jpeg", "png"])
# 
# if uploaded_file is not None:
#     image = Image.open(uploaded_file).convert("RGB")
# 
#     uploaded_file.seek(0)
#     image_bytes = uploaded_file.read()
# 
#     col_left, col_right = st.columns([1, 1])
# 
#     with col_left:
#         st.subheader("Uploaded Image")
#         st.image(image, use_container_width=True)
# 
#         st.write("---")
#         st.subheader("Cloud AI Comparison")
# 
#         # GPT-4o Button & Output
#         if st.button("🤖 Classify with GPT-4o"):
#             with st.spinner("Querying GPT-4o..."):
#                gpt_prediction = classify_image_with_gpt(image_bytes, class_names)
#                st.info(f"**GPT-4o Prediction:** {gpt_prediction}")
# 
#         # Gemini Button & Output
#         if st.button("✨ Classify with Gemini"):
#             with st.spinner("Querying Gemini..."):
#                 gemini_prediction = classify_image_with_gemini(image, class_names)
#                 st.info(f"**Gemini Prediction:** {gemini_prediction}")
# 
#     with col_right:
#         st.subheader("Prediction Results")
#         with st.spinner("Classifying with SimpleCNN..."):
#             input_tensor = transform(image).unsqueeze(0).to(device)
# 
#             with torch.no_grad():
#                 outputs = model(input_tensor)
#                 probabilities = F.softmax(outputs, dim=1)[0]
#                 conf, pred_idx = torch.max(probabilities, 0)
# 
#             predicted_class = class_names[pred_idx.item()]
#             confidence_score = conf.item() * 100
# 
#             st.success(f"**CNN Prediction:** {predicted_class}")
#             st.metric(label="CNN Confidence Score", value=f"{confidence_score:.2f}%")
# 
#         st.write("---")
#         st.write("**CNN Class Probabilities:**")
#         for i, name in enumerate(class_names):
#             prob = probabilities[i].item()
#             st.progress(prob, text=f"{name}: {prob*100:.1f}%")