# -*- coding: utf-8 -*-
"""README.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zV91oR5akJl-3tAwU44PjQIRakZ_E5p
"""

# 🍲 Food-11 Multi-Model Image Classifier & Web App

An end-to-end deep learning project featuring a custom Convolutional Neural Network (CNN) built from scratch in PyTorch to classify food images across **11 distinct categories**. The repository includes automated data ingestion from Kaggle, custom training pipelines with regularization, and an interactive **Streamlit** web application hosted via **ngrok** that compares your trained model's performance side-by-side with commercial cloud vision AIs (**GPT-4o** and **Gemini**).

---

## 🚀 Features & Improvements

- **Custom CNN architecture** with 3 convolutional blocks
- **Batch Normalization** for stable training
- **Dropout + Weight Decay** to reduce overfitting
- **Global Average Pooling** for parameter efficiency
- **Class‑weighted CrossEntropy + Label Smoothing**
- **Cosine Annealing Warm Restarts** learning‑rate scheduler
- **Extensive data augmentation** (crop, flip, rotation, color jitter)
- **Confusion matrix & classification report** for evaluation

---

## 🧠 Model Architecture (Summary)

- **Conv2d → BatchNorm → ReLU → MaxPool
- **Conv2d → BatchNorm → ReLU → MaxPool
- **Conv2d → BatchNorm → ReLU → MaxPool
- **GlobalAveragePooling
- **Linear(128 → 256) → ReLU → Dropout
- **Linear(256 → 11)

---

## 📦 Installation

```bash
git clone https://github.com/<your-username>/<repo-name>.git
cd <repo-name>
pip install -r requirements.txt


## 📊 Final Results

- **Test Accuracy:** 36.84%
- **Macro F1 Score:** 0.34
- **Weighted F1 Score:** 0.34

The model shows strong performance on classes like **Vegetable‑Fruit**, **Meat**, **Soup**, and **Fried‑food**, with structured confusion among visually similar categories.

## 📂 Project Structure

```text
├── Food_Image_Classifer_MB.ipynb   # Main Google Colab notebook (Training & App deployment)
├── food11_simple_cnn.pth            # Saved state dictionary for the trained PyTorch CNN
└── app.py                           # Streamlit application script